# Generated by Django 2.1.3 on 2018-12-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
